In [ ]:
import pandas as pd
df = pd.read_csv('/content/data_cleaning_practice_600_rows.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount,Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases (Weekly)
0,CUST1447,21.0,Female,Chair,Furniture,1813.24,Bengaluru,S,White,Summer,3.1,Yes,Same Day,No,Yes,34,UPI,3
1,CUST1485,34.0,Male,Headphones,Electronics,4176.50,Bengaluru,S,Yellow,Autumn,5.0,Yes,Standard,Yes,No,27,Credit Card,5
2,CUST1215,NaN,Other,Chair,Furniture,2807.39,Kolkata,S,Blue,Spring,4.0,No,Same Day,No,Yes,58,Cash on Delivery,7
3,CUST1212,37.0,Female,Chair,Furniture,1925.50,Mumbai,M,Green,Spring,4.9,No,Same Day,No,Yes,43,Credit Card,7
4,CUST1480,120.0,Female,Jeans,Clothing,3242.18,Mumbai,XL,Green,Autumn,4.9,No,Standard,No,Yes,37,NaN,4

In [ ]:
df.isnull().sum()

Customer ID                         0
Age                                19
Gender                             19
Item Purchased                      0
Category                            0
Purchase Amount                    23
Location                           19
Size                                0
Color                               0
Season                              0
Review Rating                      21
Subscription Status                 0
Shipping Type                       0
Discount Applied                    0
Promo Code Used                     0
Previous Purchases                  0
Payment Method                     20
Frequency of Purchases (Weekly)     0
dtype: int64

In [ ]:
def to_camel_case(snake_str):
    components = snake_str.split(' ')
    return components[0].lower() + ''.join(x.title() for x in components[1:])
df.columns = [to_camel_case(col) for col in df.columns]
df.head()

,customerId,age,gender,itemPurchased,category,purchaseAmount,location,size,color,season,reviewRating,subscriptionStatus,shippingType,discountApplied,promoCodeUsed,previousPurchases,paymentMethod,frequencyOfPurchases(Weekly)
0,CUST1447,21.0,Female,Chair,Furniture,1813.24,Bengaluru,S,White,Summer,3.1,Yes,Same Day,No,Yes,34,UPI,3
1,CUST1485,34.0,Male,Headphones,Electronics,4176.50,Bengaluru,S,Yellow,Autumn,5.0,Yes,Standard,Yes,No,27,Credit Card,5
2,CUST1215,NaN,Other,Chair,Furniture,2807.39,Kolkata,S,Blue,Spring,4.0,No,Same Day,No,Yes,58,Cash on Delivery,7
3,CUST1212,37.0,Female,Chair,Furniture,1925.50,Mumbai,M,Green,Spring,4.9,No,Same Day,No,Yes,43,Credit Card,7
4,CUST1480,120.0,Female,Jeans,Clothing,3242.18,Mumbai,XL,Green,Autumn,4.9,No,Standard,No,Yes,37,NaN,4

In [ ]:
df.duplicated().sum()

np.int64(24)

In [ ]:
df.drop_duplicates(inplace=True)
df.duplicated().sum()

np.int64(0)

In [ ]:
numerical_cols = df.select_dtypes(include=['number']).columns
outliers = pd.DataFrame(columns=df.columns)
for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    col_outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    if not col_outliers.empty:
        print(f"\nOutliers in '{col}' column (using IQR method):")
        print(col_outliers[[col]])
        outliers = pd.concat([outliers, col_outliers])
if outliers.empty:
    print("No outliers detected in numerical columns based on the IQR method.")
else:
    print("\nSummary of all detected outliers:")
    outliers.drop_duplicates().head()

Outliers in 'age' column (using IQR method):
       age
4    120.0
190   99.0
331   67.0
364   75.0
425   75.0
530  135.0
572  150.0

Outliers in 'purchaseAmount' column (using IQR method):
     purchaseAmount
7          75000.00
172         6404.78
262       100000.00
305       250000.00
399        50000.00

Outliers in 'frequencyOfPurchases(Weekly)' column (using IQR method):
     frequencyOfPurchases(Weekly)
290                            40
390                            25
567                            30

Summary of all detected outliers:

/tmp/ipykernel_2995/1209910679.py:13: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  outliers = pd.concat([outliers, col_outliers])

In [ ]:
df.mean(numeric_only=True)

age                               35.605027
purchaseAmount                  3395.115935
reviewRating                       3.984712
previousPurchases                 29.444444
frequencyOfPurchases(Weekly)       4.239583
dtype: float64

In [ ]:
df.describe()

,age,purchaseAmount,reviewRating,previousPurchases,frequencyOfPurchases(Weekly)
count,557.000000,556.000000,556.000000,576.000000,576.000000
mean,35.605027,3395.115935,3.984712,29.444444,4.239583
std,13.844272,11901.968357,0.627192,17.100024,2.848932
min,18.000000,5.000000,2.000000,0.000000,1.000000
25%,26.000000,1741.245000,3.500000,15.000000,2.000000
50%,35.000000,2586.010000,4.000000,30.000000,4.000000
75%,42.000000,3395.592500,4.500000,44.000000,6.000000
max,150.000000,250000.000000,5.000000,59.000000,40.000000

In [ ]:
df[df['purchaseAmount'] > 6000]

,customerId,age,gender,itemPurchased,category,purchaseAmount,location,size,color,season,reviewRating,subscriptionStatus,shippingType,discountApplied,promoCodeUsed,previousPurchases,paymentMethod,frequencyOfPurchases(Weekly)
7,CUST1077,33.0,Male,Headphones,Electronics,75000.00,Bengaluru,XL,Red,Summer,3.6,Yes,Express,No,No,16,UPI,2
172,CUST1084,31.0,Female,Jacket,Clothing,6404.78,Pune,XS,Blue,Autumn,2.9,No,Same Day,No,No,18,Net Banking,1
262,CUST1172,22.0,Other,Headphones,Electronics,100000.00,Mumbai,L,Black,Autumn,3.0,Yes,Standard,Yes,Yes,55,Net Banking,3
305,CUST1003,29.0,Male,Phone,Electronics,250000.00,Delhi,XS,Black,Autumn,4.7,No,Standard,No,Yes,48,Net Banking,3
399,CUST1371,37.0,Female,Sofa,Furniture,50000.00,Mumbai,M,Green,Autumn,4.9,No,Standard,No,Yes,1,Cash on Delivery,7

In [ ]:
df['reviewRating'] = df.groupby('category')['reviewRating'].transform(lambda x: x.fillna(x.mean()))
df.isnull().sum()

customerId                       0
age                             19
gender                          19
itemPurchased                    0
category                         0
purchaseAmount                  20
location                        19
size                             0
color                            0
season                           0
reviewRating                     0
subscriptionStatus               0
shippingType                     0
discountApplied                  0
promoCodeUsed                    0
previousPurchases                0
paymentMethod                   20
frequencyOfPurchases(Weekly)     0
dtype: int64

In [ ]:
df[df['customerId'] == 'CUST1480']

,customerId,age,gender,itemPurchased,category,purchaseAmount,location,size,color,season,reviewRating,subscriptionStatus,shippingType,discountApplied,promoCodeUsed,previousPurchases,paymentMethod,frequencyOfPurchases(Weekly)
4,CUST1480,120.0,Female,Jeans,Clothing,3242.18,Mumbai,XL,Green,Autumn,4.9,No,Standard,No,Yes,37,NaN,4

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
import numpy as np

# Identify rows with and without missing 'paymentMethod'
df_missing_payment = df[df['paymentMethod'].isna()]

# Check if there are any missing values to impute
if df_missing_payment.empty:
    print("No missing values found in 'paymentMethod'. Imputation not needed.")
    print("Current null values in 'paymentMethod':", df['paymentMethod'].isnull().sum())
else:
    df_train = df[df['paymentMethod'].notna()].copy()
    df_predict = df_missing_payment.copy()

    # Define features to use for prediction (choosing mostly clean columns)
    features = [
        'itemPurchased', 'category', 'size', 'color', 'season',
        'reviewRating', 'subscriptionStatus', 'shippingType', 'discountApplied',
        'promoCodeUsed', 'previousPurchases', 'frequencyOfPurchases(Weekly)'
    ]

    # Separate target variable for the training set
    X_train = df_train[features]
    y_train = df_train['paymentMethod']

    # Separate features for the prediction set
    X_predict = df_predict[features]

    # Identify categorical and numerical features for preprocessing
    categorical_features = X_train.select_dtypes(include='object').columns
    numerical_features = X_train.select_dtypes(include=['int64', 'float64']).columns

    # Create a preprocessor using ColumnTransformer for one-hot encoding categorical features
    preprocessor = ColumnTransformer(
        transformers=[
            ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
        ],
        remainder='passthrough' # Keep numerical features as they are
    )

    # Create a pipeline with preprocessing and RandomForestClassifier
    model = Pipeline(steps=[
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier(random_state=42))
    ])

    # Fit the model on the training data
    model.fit(X_train, y_train)

    # Predict the missing 'paymentMethod' values
    predicted_payment_methods = model.predict(X_predict)

    # Fill the null values in the original DataFrame
    df.loc[df['paymentMethod'].isna(), 'paymentMethod'] = predicted_payment_methods

    print("Null values in 'paymentMethod' after ML imputation:")
    print(df['paymentMethod'].isnull().sum())
    print("\nFirst 5 imputed values (if any):")
    print(df_predict.head(5)[['customerId', 'paymentMethod']].assign(predicted_paymentMethod=predicted_payment_methods[:5]))

    # Display the count of each payment method to see the distribution after imputation
    print("\nPayment Method distribution after imputation:")
    print(df['paymentMethod'].value_counts())

Null values in 'paymentMethod' after ML imputation:
0

First 5 imputed values (if any):
    customerId paymentMethod predicted_paymentMethod
4     CUST1480           NaN             Credit Card
21    CUST1148           NaN             Credit Card
65    CUST1300           NaN             Credit Card
98    CUST1417           NaN        Cash on Delivery
112   CUST1072           NaN                     UPI

Payment Method distribution after imputation:
paymentMethod
Credit Card         123
Cash on Delivery    116
UPI                 115
Net Banking         115
Debit Card          107
Name: count, dtype: int64

In [ ]:
# Function to cap outliers using IQR method
def cap_outliers_iqr(df_col):
    Q1 = df_col.quantile(0.25)
    Q3 = df_col.quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df_col = df_col.clip(lower=lower_bound, upper=upper_bound)
    return df_col

# Apply outlier capping to relevant numerical columns
for col in ['age', 'purchaseAmount', 'frequencyOfPurchases(Weekly)']:
    if col in df.columns:
        print(f"Capping outliers for column: {col}")
        df[col] = cap_outliers_iqr(df[col])
    else:
        print(f"Column '{col}' not found in DataFrame.")

print("Outliers capped successfully.")

# Verify the changes by re-running the outlier detection (optional)
# This will show if any new outliers were created or if existing ones are still outside the capped range.

numerical_cols = df.select_dtypes(include=['number']).columns
outliers_after_capping = pd.DataFrame(columns=df.columns)

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    col_outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    if not col_outliers.empty:
        print(f"\nRemaining outliers in '{col}' after capping (using IQR method):")
        print(col_outliers[[col]])
        outliers_after_capping = pd.concat([outliers_after_capping, col_outliers])

if outliers_after_capping.empty:
    print("\nNo outliers detected in numerical columns after capping based on the IQR method (for the capped columns).")
else:
    print("\nSummary of remaining detected outliers (should be none for capped columns):")
    print(outliers_after_capping.drop_duplicates().head())

Capping outliers for column: age
Capping outliers for column: purchaseAmount
Capping outliers for column: frequencyOfPurchases(Weekly)
Outliers capped successfully.

Remaining outliers in 'reviewRating' after capping (using IQR method):
     reviewRating
401           2.0
508           2.2

Summary of remaining detected outliers (should be none for capped columns):
    customerId   age  gender itemPurchased     category  purchaseAmount  \
401   CUST1279  34.0    Male          Book        Books         3426.04
508   CUST1546  32.0  Female         Watch  Accessories         1306.78

      location size   color  season  reviewRating subscriptionStatus  \
401      Delhi   XS  Yellow  Summer           2.0                 No
508  Bengaluru   XL   Green  Winter           2.2                 No

    shippingType discountApplied promoCodeUsed previousPurchases  \
401     Standard              No            No                24
508     Standard              No            No                16

    paymentMethod frequencyOfPurchases(Weekly)
401           UPI                            4
508   Net Banking                            4

/tmp/ipykernel_2995/3735214288.py:37: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  outliers_after_capping = pd.concat([outliers_after_capping, col_outliers])

In [ ]:
df.isnull().sum()

customerId                       0
age                             19
gender                          19
itemPurchased                    0
category                         0
purchaseAmount                  20
location                        19
size                             0
color                            0
season                           0
reviewRating                     0
subscriptionStatus               0
shippingType                     0
discountApplied                  0
promoCodeUsed                    0
previousPurchases                0
paymentMethod                    0
frequencyOfPurchases(Weekly)     0
dtype: int64

In [ ]:
df[df['customerId'] == 'CUST1480']

,customerId,age,gender,itemPurchased,category,purchaseAmount,location,size,color,season,reviewRating,subscriptionStatus,shippingType,discountApplied,promoCodeUsed,previousPurchases,paymentMethod,frequencyOfPurchases(Weekly)
4,CUST1480,64.5,Female,Jeans,Clothing,3242.18,Mumbai,XL,Green,Autumn,4.9,No,Standard,No,Yes,37,Credit Card,4

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify rows with and without missing 'location'
df_missing_location = df[df['location'].isna()]

# Check if there are any missing values to impute
if df_missing_location.empty:
    print("No missing values found in 'location'. Imputation not needed.")
    print("Current null values in 'location':", df['location'].isnull().sum())
else:
    df_train_loc = df[df['location'].notna()].copy()
    df_predict_loc = df_missing_location.copy()

    # Define features to use for predicting 'location'
    # Exclude 'customerId', 'location' itself, and other columns with many original nulls if not handled.
    features_for_location = [
        'age', 'gender', 'itemPurchased', 'category', 'purchaseAmount',
        'size', 'color', 'season', 'reviewRating', 'subscriptionStatus',
        'shippingType', 'discountApplied', 'promoCodeUsed', 'previousPurchases',
        'paymentMethod', 'frequencyOfPurchases(Weekly)'
    ]

    # Handle nulls in features for prediction (e.g., age, gender, purchaseAmount) to avoid issues
    # For simplicity, filling numerical with mean and categorical with mode for training/prediction features
    for col in ['age', 'purchaseAmount']:
        if col in features_for_location:
            mean_val = df_train_loc[col].mean()
            df_train_loc[col].fillna(mean_val, inplace=True)
            df_predict_loc[col].fillna(mean_val, inplace=True)

    for col in ['gender']:
        if col in features_for_location:
            mode_val = df_train_loc[col].mode()[0]
            df_train_loc[col].fillna(mode_val, inplace=True)
            df_predict_loc[col].fillna(mode_val, inplace=True)

    # Separate target variable for the training set
    X_train_loc = df_train_loc[features_for_location]
    y_train_loc = df_train_loc['location']

    # Separate features for the prediction set
    X_predict_loc = df_predict_loc[features_for_location]

    # Identify categorical and numerical features for preprocessing
    categorical_features_loc = X_train_loc.select_dtypes(include='object').columns
    numerical_features_loc = X_train_loc.select_dtypes(include=['int64', 'float64']).columns

    # Create a preprocessor using ColumnTransformer for one-hot encoding categorical features
    preprocessor_loc = ColumnTransformer(
        transformers=[
            ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features_loc)
        ],
        remainder='passthrough' # Keep numerical features as they are
    )

    # Create a pipeline with preprocessing and RandomForestClassifier
    model_loc = Pipeline(steps=[
        ('preprocessor', preprocessor_loc),
        ('classifier', RandomForestClassifier(random_state=42))
    ])

    # Fit the model on the training data
    model_loc.fit(X_train_loc, y_train_loc)

    # Predict the missing 'location' values
    predicted_locations = model_loc.predict(X_predict_loc)

    # Fill the null values in the original DataFrame
    df.loc[df['location'].isna(), 'location'] = predicted_locations

    print("Null values in 'location' after ML imputation:")
    print(df['location'].isnull().sum())
    print("\nFirst 5 imputed values (if any):")
    print(df_predict_loc.head(5)[['customerId', 'location']].assign(predicted_location=predicted_locations[:5]))

    # Display the count of each location to see the distribution after imputation
    print("\nLocation distribution after imputation:")
    print(df['location'].value_counts())

/tmp/ipykernel_2995/119147018.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train_loc[col].fillna(mean_val, inplace=True)
/tmp/ipykernel_2995/119147018.py:32: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_predict_loc[col].fillna(mean_val, inplace=True)
/tmp/ipykernel_2995/119147018.py:37: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train_loc[col].fillna(mode_val, inplace=True)
/tmp/ipykernel_2995/119147018.py:38: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_predict_loc[col].fillna(mode_val, inplace=True)

Null values in 'location' after ML imputation:
0

First 5 imputed values (if any):
    customerId location predicted_location
82    CUST1398      NaN          Bengaluru
100   CUST1203      NaN            Kolkata
131   CUST1496      NaN            Kolkata
156   CUST1390      NaN             Mumbai
163   CUST1563      NaN            Kolkata

Location distribution after imputation:
location
Kolkata      97
Hyderabad    91
Bengaluru    85
Delhi        82
Mumbai       81
Pune         75
Chennai      65
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

customerId                       0
age                             19
gender                          19
itemPurchased                    0
category                         0
purchaseAmount                  20
location                         0
size                             0
color                            0
season                           0
reviewRating                     0
subscriptionStatus               0
shippingType                     0
discountApplied                  0
promoCodeUsed                    0
previousPurchases                0
paymentMethod                    0
frequencyOfPurchases(Weekly)     0
dtype: int64

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify rows with and without missing 'purchaseAmount'
df_missing_purchase = df[df['purchaseAmount'].isna()]

# Check if there are any missing values to impute
if df_missing_purchase.empty:
    print("No missing values found in 'purchaseAmount'. Imputation not needed.")
    print("Current null values in 'purchaseAmount':", df['purchaseAmount'].isnull().sum())
else:
    df_train_purchase = df[df['purchaseAmount'].notna()].copy()
    df_predict_purchase = df_missing_purchase.copy()

    # Define features to use for predicting 'purchaseAmount'
    # Exclude 'customerId', 'purchaseAmount' itself
    features_for_purchase = [
        'age', 'gender', 'itemPurchased', 'category', 'location',
        'size', 'color', 'season', 'reviewRating', 'subscriptionStatus',
        'shippingType', 'discountApplied', 'promoCodeUsed', 'previousPurchases',
        'paymentMethod', 'frequencyOfPurchases(Weekly)'
    ]

    # Handle nulls in features for prediction (e.g., age, reviewRating) to avoid issues
    for col in ['age', 'reviewRating']:
        if col in features_for_purchase:
            mean_val = df_train_purchase[col].mean()
            df_train_purchase[col].fillna(mean_val, inplace=True)
            df_predict_purchase[col].fillna(mean_val, inplace=True)

    for col in ['gender']:
        if col in features_for_purchase:
            mode_val = df_train_purchase[col].mode()[0]
            df_train_purchase[col].fillna(mode_val, inplace=True)
            df_predict_purchase[col].fillna(mode_val, inplace=True)

    # Separate target variable for the training set
    X_train_purchase = df_train_purchase[features_for_purchase]
    y_train_purchase = df_train_purchase['purchaseAmount']

    # Separate features for the prediction set
    X_predict_purchase = df_predict_purchase[features_for_purchase]

    # Identify categorical and numerical features for preprocessing
    categorical_features_purchase = X_train_purchase.select_dtypes(include='object').columns
    numerical_features_purchase = X_train_purchase.select_dtypes(include=['int64', 'float64']).columns

    # Create a preprocessor using ColumnTransformer for one-hot encoding categorical features
    preprocessor_purchase = ColumnTransformer(
        transformers=[
            ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features_purchase)
        ],
        remainder='passthrough' # Keep numerical features as they are
    )

    # Create a pipeline with preprocessing and RandomForestRegressor
    model_purchase = Pipeline(steps=[
        ('preprocessor', preprocessor_purchase),
        ('regressor', RandomForestRegressor(random_state=42))
    ])

    # Fit the model on the training data
    model_purchase.fit(X_train_purchase, y_train_purchase)

    # Predict the missing 'purchaseAmount' values
    predicted_amounts = model_purchase.predict(X_predict_purchase)

    # Fill the null values in the original DataFrame
    df.loc[df['purchaseAmount'].isna(), 'purchaseAmount'] = predicted_amounts

    print("Null values in 'purchaseAmount' after ML imputation:")
    print(df['purchaseAmount'].isnull().sum())
    print("\nFirst 5 imputed values (if any):")
    print(df_predict_purchase.head(5)[['customerId', 'purchaseAmount']].assign(predicted_purchaseAmount=predicted_amounts[:5]))

    # Display descriptive statistics after imputation to see the effect
    print("\nDescriptive statistics for 'purchaseAmount' after imputation:")
    print(df['purchaseAmount'].describe())

/tmp/ipykernel_2995/3603174726.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train_purchase[col].fillna(mean_val, inplace=True)
/tmp/ipykernel_2995/3603174726.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_predict_purchase[col].fillna(mean_val, inplace=True)
/tmp/ipykernel_2995/3603174726.py:36: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train_purchase[col].fillna(mode_val, inplace=True)
/tmp/ipykernel_2995/3603174726.py:37: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_predict_purchase[col].fillna(mode_val, inplace=True)

Null values in 'purchaseAmount' after ML imputation:
0

First 5 imputed values (if any):
   customerId  purchaseAmount  predicted_purchaseAmount
23   CUST1587             NaN               2059.832800
41   CUST1039             NaN               2516.961000
68   CUST1535             NaN               2655.748100
83   CUST1405             NaN               2653.986900
84   CUST1209             NaN               2966.577875

Descriptive statistics for 'purchaseAmount' after imputation:
count     576.000000
mean     2582.961291
std      1201.545926
min         5.000000
25%      1768.097500
50%      2588.585000
75%      3374.245000
max      5877.113750
Name: purchaseAmount, dtype: float64

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify rows with and without missing 'age'
df_missing_age = df[df['age'].isna()]

# Check if there are any missing values to impute
if df_missing_age.empty:
    print("No missing values found in 'age'. Imputation not needed.")
    print("Current null values in 'age':", df['age'].isnull().sum())
else:
    df_train_age = df[df['age'].notna()].copy()
    df_predict_age = df_missing_age.copy()

    # Define features to use for predicting 'age'
    # Exclude 'customerId', 'age' itself
    features_for_age = [
        'gender', 'itemPurchased', 'category', 'purchaseAmount', 'location',
        'size', 'color', 'season', 'reviewRating', 'subscriptionStatus',
        'shippingType', 'discountApplied', 'promoCodeUsed', 'previousPurchases',
        'paymentMethod', 'frequencyOfPurchases(Weekly)'
    ]

    # Handle nulls in features for prediction (e.g., gender) to avoid issues
    for col in ['gender']:
        if col in features_for_age:
            mode_val = df_train_age[col].mode()[0]
            df_train_age[col].fillna(mode_val, inplace=True)
            df_predict_age[col].fillna(mode_val, inplace=True)

    for col in ['reviewRating']:
        if col in features_for_age:
            mean_val = df_train_age[col].mean()
            df_train_age[col].fillna(mean_val, inplace=True)
            df_predict_age[col].fillna(mean_val, inplace=True)


    # Separate target variable for the training set
    X_train_age = df_train_age[features_for_age]
    y_train_age = df_train_age['age']

    # Separate features for the prediction set
    X_predict_age = df_predict_age[features_for_age]

    # Identify categorical and numerical features for preprocessing
    categorical_features_age = X_train_age.select_dtypes(include='object').columns
    numerical_features_age = X_train_age.select_dtypes(include=['int64', 'float64']).columns

    # Create a preprocessor using ColumnTransformer for one-hot encoding categorical features
    preprocessor_age = ColumnTransformer(
        transformers=[
            ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features_age)
        ],
        remainder='passthrough' # Keep numerical features as they are
    )

    # Create a pipeline with preprocessing and RandomForestRegressor
    model_age = Pipeline(steps=[
        ('preprocessor', preprocessor_age),
        ('regressor', RandomForestRegressor(random_state=42))
    ])

    # Fit the model on the training data
    model_age.fit(X_train_age, y_train_age)

    # Predict the missing 'age' values
    predicted_ages = model_age.predict(X_predict_age)

    # Fill the null values in the original DataFrame
    df.loc[df['age'].isna(), 'age'] = predicted_ages

    print("Null values in 'age' after ML imputation:")
    print(df['age'].isnull().sum())
    print("\nFirst 5 imputed values (if any):")
    print(df_predict_age.head(5)[['customerId', 'age']].assign(predicted_age=predicted_ages[:5]))

    # Display descriptive statistics after imputation to see the effect
    print("\nDescriptive statistics for 'age' after imputation:")
    print(df['age'].describe())

/tmp/ipykernel_2995/262432209.py:30: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train_age[col].fillna(mode_val, inplace=True)
/tmp/ipykernel_2995/262432209.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_predict_age[col].fillna(mode_val, inplace=True)
/tmp/ipykernel_2995/262432209.py:36: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train_age[col].fillna(mean_val, inplace=True)
/tmp/ipykernel_2995/262432209.py:37: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_predict_age[col].fillna(mean_val, inplace=True)

Null values in 'age' after ML imputation:
0

First 5 imputed values (if any):
    customerId  age  predicted_age
2     CUST1215  NaN          32.43
19    CUST1286  NaN          29.77
55    CUST1311  NaN          38.53
149   CUST1548  NaN          35.69
155   CUST1023  NaN          35.85

Descriptive statistics for 'age' after imputation:
count    576.000000
mean      35.146684
std       11.412709
min       18.000000
25%       27.000000
50%       35.000000
75%       42.000000
max       66.000000
Name: age, dtype: float64

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Identify rows with and without missing 'gender'
df_missing_gender = df[df['gender'].isna()]

# Check if there are any missing values to impute
if df_missing_gender.empty:
    print("No missing values found in 'gender'. Imputation not needed.")
    print("Current null values in 'gender':", df['gender'].isnull().sum())
else:
    df_train_gen = df[df['gender'].notna()].copy()
    df_predict_gen = df_missing_gender.copy()

    # Define features to use for predicting 'gender'
    # Exclude 'customerId', 'gender' itself
    features_for_gender = [
        'age', 'itemPurchased', 'category', 'purchaseAmount', 'location',
        'size', 'color', 'season', 'reviewRating', 'subscriptionStatus',
        'shippingType', 'discountApplied', 'promoCodeUsed', 'previousPurchases',
        'paymentMethod', 'frequencyOfPurchases(Weekly)'
    ]

    # Handle nulls in features for prediction (e.g., age, purchaseAmount, reviewRating) to avoid issues
    # These columns should already be handled by previous steps, but re-filling for safety
    for col in ['age', 'purchaseAmount', 'reviewRating']:
        if col in features_for_gender:
            mean_val = df_train_gen[col].mean()
            df_train_gen[col].fillna(mean_val, inplace=True)
            df_predict_gen[col].fillna(mean_val, inplace=True)

    # Separate target variable for the training set
    X_train_gen = df_train_gen[features_for_gender]
    y_train_gen = df_train_gen['gender']

    # Separate features for the prediction set
    X_predict_gen = df_predict_gen[features_for_gender]

    # Identify categorical and numerical features for preprocessing
    categorical_features_gen = X_train_gen.select_dtypes(include='object').columns
    numerical_features_gen = X_train_gen.select_dtypes(include=['int64', 'float64']).columns

    # Create a preprocessor using ColumnTransformer for one-hot encoding categorical features
    preprocessor_gen = ColumnTransformer(
        transformers=[
            ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features_gen)
        ],
        remainder='passthrough' # Keep numerical features as they are
    )

    # Create a pipeline with preprocessing and RandomForestClassifier
    model_gen = Pipeline(steps=[
        ('preprocessor', preprocessor_gen),
        ('classifier', RandomForestClassifier(random_state=42))
    ])

    # Fit the model on the training data
    model_gen.fit(X_train_gen, y_train_gen)

    # Predict the missing 'gender' values
    predicted_genders = model_gen.predict(X_predict_gen)

    # Fill the null values in the original DataFrame
    df.loc[df['gender'].isna(), 'gender'] = predicted_genders

    print("Null values in 'gender' after ML imputation:")
    print(df['gender'].isnull().sum())
    print("\nFirst 5 imputed values (if any):")
    print(df_predict_gen.head(5)[['customerId', 'gender']].assign(predicted_gender=predicted_genders[:5]))

    # Display the count of each gender to see the distribution after imputation
    print("\nGender distribution after imputation:")
    print(df['gender'].value_counts())

/tmp/ipykernel_2995/4157089583.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_train_gen[col].fillna(mean_val, inplace=True)
/tmp/ipykernel_2995/4157089583.py:32: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_predict_gen[col].fillna(mean_val, inplace=True)

Null values in 'gender' after ML imputation:
0

First 5 imputed values (if any):
    customerId gender predicted_gender
49    CUST1344    NaN           Female
74    CUST1543    NaN             Male
80    CUST1369    NaN           Female
144   CUST1541    NaN            Other
154   CUST1079    NaN           Female

Gender distribution after imputation:
gender
Other     198
Female    193
Male      185
Name: count, dtype: int64

In [ ]:
df.isnull().sum()

customerId                      0
age                             0
gender                          0
itemPurchased                   0
category                        0
purchaseAmount                  0
location                        0
size                            0
color                           0
season                          0
reviewRating                    0
subscriptionStatus              0
shippingType                    0
discountApplied                 0
promoCodeUsed                   0
previousPurchases               0
paymentMethod                   0
frequencyOfPurchases(Weekly)    0
dtype: int64

In [ ]:
numerical_cols = df.select_dtypes(include=['number']).columns
outliers = pd.DataFrame(columns=df.columns)

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    col_outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    if not col_outliers.empty:
        print(f"\nOutliers in '{col}' column (using IQR method):")
        print(col_outliers[[col]])
        outliers = pd.concat([outliers, col_outliers])

if outliers.empty:
    print("No outliers detected in numerical columns based on the IQR method.")
else:
    print("\nSummary of all detected outliers:")
    print(outliers.drop_duplicates().head())

Outliers in 'age' column (using IQR method):
      age
4    66.0
130  65.0
190  66.0
309  65.0
331  66.0
364  66.0
425  66.0
524  65.0
530  66.0
572  66.0
579  66.0

Outliers in 'purchaseAmount' column (using IQR method):
     purchaseAmount
7        5877.11375
172      5877.11375
262      5877.11375
305      5877.11375
399      5877.11375

Outliers in 'reviewRating' column (using IQR method):
     reviewRating
401           2.0
508           2.2

Summary of all detected outliers:
    customerId   age  gender itemPurchased     category  purchaseAmount  \
4     CUST1480  66.0  Female         Jeans     Clothing         3242.18
130   CUST1477  65.0  Female          Sofa    Furniture         3041.96
190   CUST1522  66.0  Female    Headphones  Electronics          840.56
309   CUST1393  65.0   Other         Jeans     Clothing         2651.74
331   CUST1467  66.0  Female       T-Shirt     Clothing         2307.84

      location size   color  season  reviewRating subscriptionStatus  \
4       Mumbai   XL   Green  Autumn         4.900                 No
130  Bengaluru    S  Yellow  Summer         3.200                 No
190     Mumbai   XL    Blue  Summer         3.500                 No
309     Mumbai   XS  Yellow  Summer         3.948                 No
331    Chennai    L  Yellow  Autumn         4.500                Yes

    shippingType discountApplied promoCodeUsed previousPurchases  \
4       Standard              No           Yes                37
130     Standard             Yes            No                52
190      Express             Yes            No                54
309     Same Day             Yes            No                54
331     Same Day             Yes            No                36

        paymentMethod frequencyOfPurchases(Weekly)
4         Credit Card                            4
130       Net Banking                            2
190  Cash on Delivery                            7
309        Debit Card                            4
331               UPI                            1

/tmp/ipykernel_2995/2105953601.py:15: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  outliers = pd.concat([outliers, col_outliers])

In [ ]:
# Re-apply outlier capping to 'age', 'purchaseAmount', and 'reviewRating'
# using the existing 'cap_outliers_iqr' function defined previously.

print("Re-capping outliers for columns: 'age', 'purchaseAmount', 'reviewRating'")
for col in ['age', 'purchaseAmount', 'reviewRating']:
    if col in df.columns:
        df[col] = cap_outliers_iqr(df[col])
        print(f"Outliers in '{col}' re-capped successfully.")
    else:
        print(f"Column '{col}' not found in DataFrame.")

print("Outlier re-capping complete.")

Re-capping outliers for columns: 'age', 'purchaseAmount', 'reviewRating'
Outliers in 'age' re-capped successfully.
Outliers in 'purchaseAmount' re-capped successfully.
Outliers in 'reviewRating' re-capped successfully.
Outlier re-capping complete.

In [ ]:
numerical_cols = df.select_dtypes(include=['number']).columns
outliers = pd.DataFrame(columns=df.columns)

for col in numerical_cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    col_outliers = df[(df[col] < lower_bound) | (df[col] > upper_bound)]
    if not col_outliers.empty:
        print(f"\nOutliers in '{col}' column (using IQR method):")
        print(col_outliers[[col]])
        outliers = pd.concat([outliers, col_outliers])

if outliers.empty:
    print("\nNo outliers detected in numerical columns based on the IQR method.")
else:
    print("\nSummary of all detected outliers after re-capping:")
    print(outliers.drop_duplicates().head())

No outliers detected in numerical columns based on the IQR method.

In [ ]:
df

,customerId,age,gender,itemPurchased,category,purchaseAmount,location,size,color,season,reviewRating,subscriptionStatus,shippingType,discountApplied,promoCodeUsed,previousPurchases,paymentMethod,frequencyOfPurchases(Weekly)
0,CUST1447,21.00,Female,Chair,Furniture,1813.24,Bengaluru,S,White,Summer,3.1,Yes,Same Day,No,Yes,34,UPI,3
1,CUST1485,34.00,Male,Headphones,Electronics,4176.50,Bengaluru,S,Yellow,Autumn,5.0,Yes,Standard,Yes,No,27,Credit Card,5
2,CUST1215,32.43,Other,Chair,Furniture,2807.39,Kolkata,S,Blue,Spring,4.0,No,Same Day,No,Yes,58,Cash on Delivery,7
3,CUST1212,37.00,Female,Chair,Furniture,1925.50,Mumbai,M,Green,Spring,4.9,No,Same Day,No,Yes,43,Credit Card,7
4,CUST1480,64.50,Female,Jeans,Clothing,3242.18,Mumbai,XL,Green,Autumn,4.9,No,Standard,No,Yes,37,Credit Card,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
595,CUST1474,32.00,Female,Phone,Electronics,1315.38,Mumbai,XL,Black,Summer,3.9,No,Standard,No,No,57,Cash on Delivery,3
596,CUST1560,35.00,Male,Laptop,Electronics,2953.27,Delhi,S,Blue,Autumn,4.8,Yes,Express,No,Yes,46,UPI,4
597,CUST1252,40.00,Other,Book,Books,3229.02,Hyderabad,L,Red,Spring,3.3,Yes,Express,Yes,No,52,Cash on Delivery,4
598,CUST1021,53.00,Female,Watch,Accessories,2319.36,Kolkata,XS,Blue,Summer,3.3,Yes,Same Day,No,Yes,50,Net Banking,7
599,CUST1313,32.00,Female,Watch,Accessories,1336.96,Chennai,XS,Blue,Winter,4.4,No,Express,Yes,Yes,12,Cash on Delivery,7

In [ ]:
duplicate_columns = df.T.duplicated(keep=False)
duplicate_columns

KeyError: 'duplicate_columns'

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 576 entries, 0 to 599
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   customerId                    576 non-null    object
 1   age                           576 non-null    float64
 2   gender                        576 non-null    object
 3   itemPurchased                 576 non-null    object
 4   category                      576 non-null    object
 5   purchaseAmount                576 non-null    float64
 6   location                      576 non-null    object
 7   size                          576 non-null    object
 8   color                         576 non-null    object
 9   season                        576 non-null    object
 10  reviewRating                  576 non-null    float64
 11  subscriptionStatus            576 non-null    object
 12  shippingType                  576 non-null    object
 13  discountApplied               576 non-null    object
 14  promoCodeUsed                 576 non-null    object
 15  previousPurchases             576 non-null    int64
 16  paymentMethod                 576 non-null    object
 17  frequencyOfPurchases(Weekly)  576 non-null    int64
dtypes: float64(3), int64(2), object(13)
memory usage: 85.5+ KB

In [ ]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
595    False
596    False
597    False
598    False
599    False
Length: 576, dtype: bool

In [ ]:
df.rename(columns={'frequencyOfPurchases(Weekly)': 'frequencyOfPurchasesWeekly'}, inplace=True)
df.head()